/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TogglebuttongroupRouteImport } from './routes/togglebuttongroup'
import { Route as TogglebuttonRouteImport } from './routes/togglebutton'
import { Route as ToastRouteImport } from './routes/toast'
import { Route as TextareaRouteImport } from './routes/textarea'
import { Route as SliderRouteImport } from './routes/slider'
import { Route as PositionpadRouteImport } from './routes/positionpad'
import { Route as InputRouteImport } from './routes/input'
import { Route as IconsRouteImport } from './routes/icons'
import { Route as FontsRouteImport } from './routes/fonts'
import { Route as DropdownRouteImport } from './routes/dropdown'
import { Route as ColorsRouteImport } from './routes/colors'
import { Route as CheckboxRouteImport } from './routes/checkbox'
import { Route as ButtonRouteImport } from './routes/button'
import { Route as IndexRouteImport } from './routes/index'

const TogglebuttongroupRoute = TogglebuttongroupRouteImport.update({
  id: '/togglebuttongroup',
  path: '/togglebuttongroup',
  getParentRoute: () => rootRouteImport,
} as any)
const TogglebuttonRoute = TogglebuttonRouteImport.update({
  id: '/togglebutton',
  path: '/togglebutton',
  getParentRoute: () => rootRouteImport,
} as any)
const ToastRoute = ToastRouteImport.update({
  id: '/toast',
  path: '/toast',
  getParentRoute: () => rootRouteImport,
} as any)
const TextareaRoute = TextareaRouteImport.update({
  id: '/textarea',
  path: '/textarea',
  getParentRoute: () => rootRouteImport,
} as any)
const SliderRoute = SliderRouteImport.update({
  id: '/slider',
  path: '/slider',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionpadRoute = PositionpadRouteImport.update({
  id: '/positionpad',
  path: '/positionpad',
  getParentRoute: () => rootRouteImport,
} as any)
const InputRoute = InputRouteImport.update({
  id: '/input',
  path: '/input',
  getParentRoute: () => rootRouteImport,
} as any)
const IconsRoute = IconsRouteImport.update({
  id: '/icons',
  path: '/icons',
  getParentRoute: () => rootRouteImport,
} as any)
const FontsRoute = FontsRouteImport.update({
  id: '/fonts',
  path: '/fonts',
  getParentRoute: () => rootRouteImport,
} as any)
const DropdownRoute = DropdownRouteImport.update({
  id: '/dropdown',
  path: '/dropdown',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorsRoute = ColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckboxRoute = CheckboxRouteImport.update({
  id: '/checkbox',
  path: '/checkbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ButtonRoute = ButtonRouteImport.update({
  id: '/button',
  path: '/button',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/button': typeof ButtonRoute
  '/checkbox': typeof CheckboxRoute
  '/colors': typeof ColorsRoute
  '/dropdown': typeof DropdownRoute
  '/fonts': typeof FontsRoute
  '/icons': typeof IconsRoute
  '/input': typeof InputRoute
  '/positionpad': typeof PositionpadRoute
  '/slider': typeof SliderRoute
  '/textarea': typeof TextareaRoute
  '/toast': typeof ToastRoute
  '/togglebutton': typeof TogglebuttonRoute
  '/togglebuttongroup': typeof TogglebuttongroupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/button': typeof ButtonRoute
  '/checkbox': typeof CheckboxRoute
  '/colors': typeof ColorsRoute
  '/dropdown': typeof DropdownRoute
  '/fonts': typeof FontsRoute
  '/icons': typeof IconsRoute
  '/input': typeof InputRoute
  '/positionpad': typeof PositionpadRoute
  '/slider': typeof SliderRoute
  '/textarea': typeof TextareaRoute
  '/toast': typeof ToastRoute
  '/togglebutton': typeof TogglebuttonRoute
  '/togglebuttongroup': typeof TogglebuttongroupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/button': typeof ButtonRoute
  '/checkbox': typeof CheckboxRoute
  '/colors': typeof ColorsRoute
  '/dropdown': typeof DropdownRoute
  '/fonts': typeof FontsRoute
  '/icons': typeof IconsRoute
  '/input': typeof InputRoute
  '/positionpad': typeof PositionpadRoute
  '/slider': typeof SliderRoute
  '/textarea': typeof TextareaRoute
  '/toast': typeof ToastRoute
  '/togglebutton': typeof TogglebuttonRoute
  '/togglebuttongroup': typeof TogglebuttongroupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/button'
    | '/checkbox'
    | '/colors'
    | '/dropdown'
    | '/fonts'
    | '/icons'
    | '/input'
    | '/positionpad'
    | '/slider'
    | '/textarea'
    | '/toast'
    | '/togglebutton'
    | '/togglebuttongroup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/button'
    | '/checkbox'
    | '/colors'
    | '/dropdown'
    | '/fonts'
    | '/icons'
    | '/input'
    | '/positionpad'
    | '/slider'
    | '/textarea'
    | '/toast'
    | '/togglebutton'
    | '/togglebuttongroup'
  id:
    | '__root__'
    | '/'
    | '/button'
    | '/checkbox'
    | '/colors'
    | '/dropdown'
    | '/fonts'
    | '/icons'
    | '/input'
    | '/positionpad'
    | '/slider'
    | '/textarea'
    | '/toast'
    | '/togglebutton'
    | '/togglebuttongroup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ButtonRoute: typeof ButtonRoute
  CheckboxRoute: typeof CheckboxRoute
  ColorsRoute: typeof ColorsRoute
  DropdownRoute: typeof DropdownRoute
  FontsRoute: typeof FontsRoute
  IconsRoute: typeof IconsRoute
  InputRoute: typeof InputRoute
  PositionpadRoute: typeof PositionpadRoute
  SliderRoute: typeof SliderRoute
  TextareaRoute: typeof TextareaRoute
  ToastRoute: typeof ToastRoute
  TogglebuttonRoute: typeof TogglebuttonRoute
  TogglebuttongroupRoute: typeof TogglebuttongroupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/togglebuttongroup': {
      id: '/togglebuttongroup'
      path: '/togglebuttongroup'
      fullPath: '/togglebuttongroup'
      preLoaderRoute: typeof TogglebuttongroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/togglebutton': {
      id: '/togglebutton'
      path: '/togglebutton'
      fullPath: '/togglebutton'
      preLoaderRoute: typeof TogglebuttonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toast': {
      id: '/toast'
      path: '/toast'
      fullPath: '/toast'
      preLoaderRoute: typeof ToastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/textarea': {
      id: '/textarea'
      path: '/textarea'
      fullPath: '/textarea'
      preLoaderRoute: typeof TextareaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slider': {
      id: '/slider'
      path: '/slider'
      fullPath: '/slider'
      preLoaderRoute: typeof SliderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positionpad': {
      id: '/positionpad'
      path: '/positionpad'
      fullPath: '/positionpad'
      preLoaderRoute: typeof PositionpadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/input': {
      id: '/input'
      path: '/input'
      fullPath: '/input'
      preLoaderRoute: typeof InputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icons': {
      id: '/icons'
      path: '/icons'
      fullPath: '/icons'
      preLoaderRoute: typeof IconsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fonts': {
      id: '/fonts'
      path: '/fonts'
      fullPath: '/fonts'
      preLoaderRoute: typeof FontsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dropdown': {
      id: '/dropdown'
      path: '/dropdown'
      fullPath: '/dropdown'
      preLoaderRoute: typeof DropdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colors': {
      id: '/colors'
      path: '/colors'
      fullPath: '/colors'
      preLoaderRoute: typeof ColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkbox': {
      id: '/checkbox'
      path: '/checkbox'
      fullPath: '/checkbox'
      preLoaderRoute: typeof CheckboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/button': {
      id: '/button'
      path: '/button'
      fullPath: '/button'
      preLoaderRoute: typeof ButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ButtonRoute: ButtonRoute,
  CheckboxRoute: CheckboxRoute,
  ColorsRoute: ColorsRoute,
  DropdownRoute: DropdownRoute,
  FontsRoute: FontsRoute,
  IconsRoute: IconsRoute,
  InputRoute: InputRoute,
  PositionpadRoute: PositionpadRoute,
  SliderRoute: SliderRoute,
  TextareaRoute: TextareaRoute,
  ToastRoute: ToastRoute,
  TogglebuttonRoute: TogglebuttonRoute,
  TogglebuttongroupRoute: TogglebuttongroupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
